name: Deploy to Environment

on:
  push:
    branches:
      - dev
      - qa
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Default permission for accessing the repo

jobs:
  # Step 1: Bootstrap Backend Resources (if not already done)
  bootstrap:
    name: Bootstrap Backend for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}  # dynamic environment based on branch (dev/qa/main)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false
          enable-AzPSSession: false

      - name: Set Azure Subscription
        run:  |
          echo "Setting Azure Subscription to: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create backend resources if not exists
        run: |
          az_backend_rg_name="iat-backend${{ github.ref_name }}"
          az_backend_sa_name="iat-backend${{ github.ref_name }}"
          az_backend_container_name="iat-backend${{ github.ref_name }}"
          az_location="SwitzerlandNorth"

          echo "Creating resource group if not exists"
          az group create --name $az_backend_rg_name --location $az_location

          echo "Creating storage account if not exists"
          az storage account create \
            --name $az_backend_sa_name \
            --resource-group $az_backend_rg_name \
            --location $az_location \
            --sku Standard_LRS --only-show-errors || echo "Storage account exists"

          echo "Waiting for storage account to be ready..."
          sleep 30

          echo "Fetching storage account key"
          STORAGE_KEY=$(az storage account keys list --resource-group $az_backend_rg_name --account-name $az_backend_sa_name --query '[0].value' -o tsv)

          echo "Creating storage container if not exists"
          az storage container create \
            --name $az_backend_container_name \
            --account-name $az_backend_sa_name \
            --account-key $STORAGE_KEY

  # Step 2: Main Terraform Deployment
  deploy:
    name: Deploy ${{ github.ref_name }} Infrastructure
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    needs: bootstrap
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: false
          enable-AzPSSession: false

      - name: Set Terraform Environment Variables
        run: |
          echo "TF_VAR_az_client_id=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_az_tenant_id=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_az_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_az_container_name=backend${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./iaac-azure-tf-website/infra
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
        run: |
          terraform init -var-file="${{ github.ref_name }}.tfvars"

      - name: Terraform Apply
        working-directory: ./iaac-azure-tf-website/infra
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform.log
        run: |
          terraform apply -var-file="${{ github.ref_name }}.tfvars" -auto-approve

      - name: Upload Terraform Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-log-${{ github.ref_name }}
          path: ./iaac-azure-tf-website/infra/terraform.log

  ###### Publish Website to Azure Web App ######

  deploy-website:
    name: Deploy ${{ github.ref_name }} Website
    runs-on: ubuntu-latest
    needs: deploy
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout Website code
        uses: actions/checkout@v3
        with:
          repository: fpittelo/website
          path: website

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Website to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          package: ./website
