name: Destroy On Azure

on:
  workflow_dispatch:  # Enables manual triggering of the workflow

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy Azure Resources With Terraform
    runs-on: ubuntu-latest
    environment: AZURE

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Login To Azure with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true
        enable-AzPSSession: false
        environment: azurecloud

    # Set environment variables for Terraform authentication
    - name: Set environment variables for Terraform
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_USE_OIDC=true" >> $GITHUB_ENV  # Important for OIDC authentication

    # Initialize Terraform with Backend
    - name: Initialize Terraform with Backend
      run: |
        terraform init -backend-config="resource_group_name=${{ env.TF_VAR_rg_name }}" \
                       -backend-config="storage_account_name=${{ env.TF_VAR_sa_name }}" \
                       -backend-config="container_name=${{ env.TF_VAR_container_name }}" \
                       -backend-config="key=terraform.tfstate" \
                       -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                       -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                       -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                       -backend-config="use_oidc=true"

    # Generate Terraform Destroy Plan (Optional, for review purposes)
    - name: Generate Terraform Destroy Plan
      run: terraform plan -destroy

    # Execute Terraform Destroy
    - name: Execute Terraform Destroy
      run: terraform destroy -auto-approve
